### ISSUE TITLE
capture by mask

### ISSUE THREAD

**Issue by sub-1337** [DanMcInerney/net-creds#11]
Please add capture POST request by mask, cap all POST requests that have "login","pass","email" field and custom phazes.

**Comment by DanMcInerney** [comment]
It should already do that. Check line 914. It checks for 'login', 'pass', and 'email'. Custom phrases might be a good idea to add. I'll keep that in mind. Just make sure when you test it you're testing it on HTTP versions of sites rather than HTTPS which it can't parse.
