### ISSUE TITLE
Import error of geteuid, devnull

### ISSUE THREAD

**Issue by ghost** [DanMcInerney/net-creds#17]
Import error of geteuid, devnull from os library
![capture](https://cloud.githubusercontent.com/assets/16590907/12207283/b4da5cba-b66b-11e5-8de3-ffe0465949bc.JPG)

**Comment by DanMcInerney** [comment]
What version of python are you using? I thought os was a standard library. This is meant to run on 2.7.

**Comment by DavidHaintz** [comment]
Same problem here.
Tried versions:
2.7.18
3.9.1 (with print-call correction)

Both on windows. 

How to reproduce? Install newest python version and run it.
Looks like it's not available for windows. 


My workaround:
Uncomment following lines:
#3 from os import geteuid, devnull
#39 DN = open("log.txt", 'w')
#986 if geteuid():
#987     exit('[-] Please run as root')
