### ISSUE TITLE
No sniffing happening with Ubuntu

### ISSUE THREAD

**Issue by danetrain** [DanMcInerney/net-creds#19]
Hello, I'm running this script on Ubuntu and it doesn't capture anything except traffic from the machine on which the script is running. I've tried enabling promiscuous mode on my wireless interface but that doesn't seem to change anything. Has anyone else seen this / have any mitigations?

**Comment by DanMcInerney** [comment]
Are you routing traffic from other hosts through your machine through perhaps ARP spoofing? That's the only way it would sniff traffic that isn't on the machine you're running it on.

**Comment by danetrain** [comment]
Yes, I've been working on pairing it up with ARP spoofing through the MITMf library, but that installation isn't straightforward, and it looks like the installation instructions are out of date. What script/utility do you typically pair with net-creds when you're using it?

**Comment by DanMcInerney** [comment]
MITMf actually uses net-creds automatically so you should try installing
that tool. Otherwise, I suppose you could use bettercap or ettercap or
arpspoof from the dsniff suite.
