### ISSUE TITLE
Argument for datetime output

### ISSUE THREAD

**Issue by colinmcintosh** [DanMcInerney/net-creds#3]
I'd like to see an argument to output the datetime with the message. Something like:

```
root@server:/root/sandbox/net-creds> python net-creds.py -d
[*] Using interface: ens33
[2015-03-04 18:26:41] [192.168.1.2] GET cnn.com/
```

Check it out: https://github.com/colinmcintosh/net-creds/tree/dev 
If you're okay with it I can send a pull request

**Comment by DanMcInerney** [comment]
This would be great send me a pull req.

**Comment by DanMcInerney** [comment]
Pull req?
